### ISSUE TITLE
Create a tooltip with Angular Ivy and Angular CDK

### ISSUE THREAD

**Issue by nartc** [tieppt/ask-me-smt#1]
- Mobile friendly
- Different triggers: click, focus, hover

**Comment by tieppt** [comment]
Accepted =)))

**Comment by tieppt** [comment]
Mình sẽ làm dropdown menu:
- [ ] Overlay cho phép config vị trí bất kỳ để hiển thị menu.
- [ ] RxJS để handle event khi hover

**Comment by tieppt** [comment]
Video live coding: https://www.youtube.com/watch?v=JrCnFX9knEE
